version: '3'
services:
  react-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      # All endpoint URLs need to be "public-facing" (names need to resolve from the browser)
      - REACT_APP_REQUESTS_URL=http://localhost:5000
      - REACT_APP_DATABASE_URL=http://localhost:8001
      - REACT_APP_MATOMO_ENDPOINT=https://support.tib.eu/piwik/index.php
      - REACT_APP_MATOMO_API_TOKEN=2f1a8c6a07609a76907dd8111dff26ed
      - REACT_APP_FRONTEND_URL=http://localhost:3000
    depends_on:
      - backend-database
      - backend-requests

  backend-database:
    build: ./src/backend-database
    ports:
      - "8001:8001"

  backend-requests:
    build: ./src/backend-requests
    ports:
      - "5000:8002"
